name: Nicola Lamacchia
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
permalink: /:categories/:year/:month/:title.html
pygments: true
keep_files: ['.git', '.hg', '.nojekyll']
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
tag_page_layout: tag_list
tag_page_dir: tag
